
echo "***"
echo "*** HEY !! You neeed to uncommend some lines in ~/.bash_profile"
echo "***"

#
# Uncomment these lines after setting up the "awskeys" directory
#
#export AWS_REGION=us-west-1
#export AWS_CREDENTIAL_FILE=~/awskeys/.awscredentials
#export EC2_PRIVATE_KEY=~/awskeys/ec2-private-key
#export EC2_CERT=~/awskeys/ec2-cert 	
#. $AWS_TOOLS/awssetup.sh

